name: Behaviour Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      WIKIPEDIA_PASSWORD: ${{ secrets.WIKIPEDIA_PASSWORD }}

    steps:
      - name: "Check out"
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Test with pytest
        run: |
          pipenv run behave