name: Behaviour Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      WIKIPEDIA_USERNAME: ${{ secrets.WIKIPEDIA_USERNAME }}
      WIKIPEDIA_PASSWORD: ${{ secrets.WIKIPEDIA_PASSWORD }}

    steps:
      - name: "Check out"
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - run: mkdir output

      - name: Test with pytest
        id: tests
        continue-on-error: True
        run: pipenv run behave

      - name: upload screenshots
        uses: actions/upload-artifact@v2
        with:
          path: output
          name: Download-screenshots
          retention-days: 1

      - name: Check for failures
        if: ${{steps.tests.outcome}} == 'failure'
        run: exit 1